[Users]
#User=1353126873864863755 (ID)  -> Don't use '#'
#Fytex=321346463148015626

[Options]
Token=MTM1NzAyNDU1Njc2NTgwNjY4NA.GlKXpQ.uJeevZ_1LmYhhiQwGLYJduwSo_eQMZgssfwOks
CooldownBypass=True
OfflineMode=False
